/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PhishBlock } from "./PhishBlock";
export * as factories from "./factories";
export { PhishBlock__factory } from "./factories/PhishBlock__factory";
